In [4]:
#高维数组
import numpy as np
import pandas as pd
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
arr=np.arange(10)
arr[5:8]=12
arr_slice=arr[5:8]
print (arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [3]:
#索引和切片
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0][2])
print(arr2d[0,2])

3
3


In [5]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [7]:
arr2d[:2,2]

array([3, 6])

In [9]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [10]:
import pandas as pd
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
print(obj)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64


In [8]:
obj2=obj.reindex(['a','b','c','d','e'])
print(obj2)

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [13]:
import pandas as pd
import numpy as np
data = pd.DataFrame(np.arange(30).reshape((6,5)),columns=['A','B','C','D','E'])
print (data)

    A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29


In [15]:
#读取第二行的值
data1 = data.loc[1]
print(data1)

A    5
B    6
C    7
D    8
E    9
Name: 1, dtype: int32


In [23]:
data7=data.iloc[0]
print(data7)

A    0
B    1
C    2
D    3
E    4
Name: 0, dtype: int32


In [16]:
#读取第二列的值
data2 = data.loc[ : ,"B"]
print(data2)

0     1
1     6
2    11
3    16
4    21
5    26
Name: B, dtype: int32


In [17]:
# 读取第1行，第B列对应的值
data3 = data.loc[ 1, "B"]
print(data3)

6


In [18]:
# 读取第1行到第3行，第B列到第D列这个区域内的值
data4 = data.loc[ 1:3, "B":"D"]
print(data4)

    B   C   D
1   6   7   8
2  11  12  13
3  16  17  18


In [19]:
# 读取第B列中大于6的值
data5 = data.loc[ data.B > 6] #等价于 data5 = data[data.B > 6]
print(data5)

    A   B   C   D   E
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29


In [21]:
# 进行切片操作，选择B，C，D，E四列区域内，B列大于6的值
data6 = data.loc[ data.B >6, ["B","C","D","E"]]
print(data1)

    B   C   D   E
2  11  12  13  14
3  16  17  18  19
4  21  22  23  24
5  26  27  28  29
