In [4]:
#高维数组
import numpy as np
import pandas as pd
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
arr=np.arange(10)
arr[5:8]=12
arr_slice=arr[5:8]
print (arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [3]:
#索引和切片
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0][2])
print(arr2d[0,2])

3
3


In [5]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [7]:
arr2d[:2,2]

array([3, 6])

In [9]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [10]:
import pandas as pd
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
print(obj)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64


In [8]:
obj2=obj.reindex(['a','b','c','d','e'])
print(obj2)

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [13]:
import pandas as pd
import numpy as np
data = pd.DataFrame(np.arange(30).reshape((6,5)),columns=['A','B','C','D','E'])
print (data)

    A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29


In [15]:
#读取第二行的值
data1 = data.loc[1]
print(data1)

A    5
B    6
C    7
D    8
E    9
Name: 1, dtype: int32


In [23]:
data7=data.iloc[0]
print(data7)

A    0
B    1
C    2
D    3
E    4
Name: 0, dtype: int32


In [16]:
#读取第二列的值
data2 = data.loc[ : ,"B"]
print(data2)

0     1
1     6
2    11
3    16
4    21
5    26
Name: B, dtype: int32


In [17]:
# 读取第1行，第B列对应的值
data3 = data.loc[ 1, "B"]
print(data3)

6


In [18]:
# 读取第1行到第3行，第B列到第D列这个区域内的值
data4 = data.loc[ 1:3, "B":"D"]
print(data4)

    B   C   D
1   6   7   8
2  11  12  13
3  16  17  18


In [19]:
# 读取第B列中大于6的值
data5 = data.loc[ data.B > 6] #等价于 data5 = data[data.B > 6]
print(data5)

    A   B   C   D   E
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29


In [21]:
# 进行切片操作，选择B，C，D，E四列区域内，B列大于6的值
data6 = data.loc[ data.B >6, ["B","C","D","E"]]
print(data1)

    B   C   D   E
2  11  12  13  14
3  16  17  18  19
4  21  22  23  24
5  26  27  28  29


In [1]:
#pipe(),apply(),applymap()操作函数，某行
import pandas as pd
import numpy as np
#自定义函数
def adder(ele1,ele2):
   return ele1+ele2
#操作DataFrame
df = pd.DataFrame(np.random.randn(4,3),columns=['c1','c2','c3'])
#相加前
print(df)
#相加后
print(df.pipe(adder,3))

         c1        c2        c3
0 -0.244149 -0.117094 -0.562897
1  1.325621  1.451623  0.091696
2 -0.622995 -0.635117 -0.527194
3 -0.519723 -0.270340 -0.506174
         c1        c2        c3
0  2.755851  2.882906  2.437103
1  4.325621  4.451623  3.091696
2  2.377005  2.364883  2.472806
3  2.480277  2.729660  2.493826


In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(5,3),columns=['col1','col2','col3'])
#df.apply(np.mean)
#默认按列操作，计算每一列均值
print(df.apply(np.mean))

print (df.apply(np.mean,axis=1))

#自定义函数lambda函数
print(df['col1'].map(lambda x:x*100))

print(df.applymap(lambda x:x*10))

col1   -0.048045
col2    0.078333
col3   -0.118020
dtype: float64
0    0.602833
1   -1.059298
2    0.404695
3   -0.772984
4    0.678533
dtype: float64
0    148.711816
1   -124.082125
2    -29.363090
3    -90.254559
4     70.965315
Name: col1, dtype: float64
        col1       col2       col3
0  14.871182   8.967777  -5.753960
1 -12.408212  -4.186987 -15.183733
2  -2.936309   0.872942  14.204230
3  -9.025456 -10.459661  -3.704405
4   7.096532   8.722581   4.536875


In [5]:
#loc[] 接受两个参数，并以','分隔。第一个位置表示行，第二个位置表示列。
import numpy as np
import pandas as pd
#创建一组数据
data = {'name': ['John', 'Mike', 'Mozla', 'Rose', 'David', 'Marry', 'Wansi', 'Sidy', 'Jack', 'Alic'],
        'age': [20, 32, 29, np.nan, 15, 28, 21, 30, 37, 25],
        'gender': [0, 0, 1, 1, 0, 1, 0, 0, 1, 1],
        'isMarried': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
label = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, index=label)
print(df)
#对行操作
print(df.loc['a':'d',:]) #等同于df.loc['a':'d']
#对列操作
print(df.loc[:,'name'])
#对行列同时操作
print(df.loc[['a','d'],['name','age']])

    name   age  gender isMarried
a   John  20.0       0       yes
b   Mike  32.0       0       yes
c  Mozla  29.0       1        no
d   Rose   NaN       1       yes
e  David  15.0       0        no
f  Marry  28.0       1        no
g  Wansi  21.0       0        no
h   Sidy  30.0       0       yes
i   Jack  37.0       1        no
j   Alic  25.0       1        no
    name   age  gender isMarried
a   John  20.0       0       yes
b   Mike  32.0       0       yes
c  Mozla  29.0       1        no
d   Rose   NaN       1       yes
a     John
b     Mike
c    Mozla
d     Rose
e    David
f    Marry
g    Wansi
h     Sidy
i     Jack
j     Alic
Name: name, dtype: object
   name   age
a  John  20.0
d  Rose   NaN


In [7]:
#df.iloc[] 只能使用整数索引，不能使用标签索引，通过整数索引切片选择数据时，前闭后开(不包含边界结束值)。同 Python 和 NumPy 一样，它们的索引都是从 0 开始
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])
print(df)
print(df.iloc[2,])
print (df.iloc[[1, 3, 5], [1, 3]])
print (df.iloc[1:3, :])
print (df.iloc[:,1:3])




          A         B         C         D
0  1.159061 -0.526825  2.199428 -0.241417
1 -0.727145 -1.146375  2.157409  0.649590
2  0.691318 -0.991345 -0.030901  0.391429
3  1.640356 -1.159359  0.698537 -0.427863
4 -0.275805  1.159488  0.824182  0.890629
5 -1.404269  2.048483  3.749100  0.539621
6 -0.830464 -0.488315  1.736284 -0.092469
7 -0.378946 -1.005187 -1.127907  0.028781
A    0.691318
B   -0.991345
C   -0.030901
D    0.391429
Name: 2, dtype: float64
          B         D
1 -1.146375  0.649590
3 -1.159359 -0.427863
5  2.048483  0.539621
          A         B         C         D
1 -0.727145 -1.146375  2.157409  0.649590
2  0.691318 -0.991345 -0.030901  0.391429
          B         C
0 -0.526825  2.199428
1 -1.146375  2.157409
2 -0.991345 -0.030901
3 -1.159359  0.698537
4  1.159488  0.824182
5  2.048483  3.749100
6 -0.488315  1.736284
7 -1.005187 -1.127907


In [10]:
"""
Pandas 提供了几种窗口函数，比如移动函数（rolling）、扩展函数（expanding）和指数加权函数（ewm）.
理解一下扩展窗口的含义：
表示至少 3 个数求一次均值，计算方式为
A2=(A0+A1+A2)/3，
A3=(A0+A1+A2+A3)/4
A4=(A0+A1+A2+A3+A4)/5
A5 A6 依次类推。
"""
import pandas as pd
import numpy as np
#生成时间序列
df = pd.DataFrame(np.random.randn(8, 4),index = pd.date_range('12/1/2020', periods=8),columns = ['A', 'B', 'C', 'D'])
print(df)
#每3个数求求一次均值
print(df.rolling(window=3).mean())

print (df.expanding(min_periods=3).mean())

#设置com=0.5，先加权再求均值
print(df.ewm(com=0.5).mean())

                   A         B         C         D
2020-12-01  0.565338  2.137809  0.355771  0.660917
2020-12-02 -1.424568 -0.744922  1.726671 -0.784041
2020-12-03  1.937914  0.964649 -0.315839 -0.485340
2020-12-04  0.038592  1.427256  0.518337 -1.158714
2020-12-05  2.044111  0.117694  1.138335 -1.786801
2020-12-06 -0.042279 -2.217036 -0.636958 -1.051224
2020-12-07 -0.050778 -0.409399  1.921651  0.164026
2020-12-08 -0.612451 -0.245027  0.836185  2.195589
                   A         B         C         D
2020-12-01       NaN       NaN       NaN       NaN
2020-12-02       NaN       NaN       NaN       NaN
2020-12-03  0.359561  0.785845  0.588868 -0.202821
2020-12-04  0.183979  0.548994  0.643056 -0.809365
2020-12-05  1.340206  0.836533  0.446944 -1.143618
2020-12-06  0.680141 -0.224029  0.339905 -1.332246
2020-12-07  0.650351 -0.836247  0.807676 -0.891333
2020-12-08 -0.235169 -0.957154  0.706960  0.436130
                   A         B         C         D
2020-12-01       NaN       NaN 