In [4]:
#高维数组
import numpy as np
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
arr=np.arange(10)
arr[5:8]=12
arr_slice=arr[5:8]
print (arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [3]:
#索引和切片
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0][2])
print(arr2d[0,2])

3
3


In [5]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [7]:
arr2d[:2,2]

array([3, 6])

In [9]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [4]:
import numpy as np
arr3=np.arange(15).reshape((3,5))
print(arr3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
print(np.reshape(arr3,(-1,1)))
print("将元素变成一行(二维)")
print(np.reshape(arr3,(1,-1)))
print("将元素变成一串（一维）")
print(np.reshape(arr3,(-1)))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
将元素变成一行(二维)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
将元素变成一串（一维）
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
#矩阵转换
arr3.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [9]:
#计算矩阵内积
arr4=np.dot(arr3.T,arr3)
arr4

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])