In [4]:
#高维数组
import numpy as np
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
arr=np.arange(10)
arr[5:8]=12
arr_slice=arr[5:8]
print (arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [3]:
#索引和切片
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0][2])
print(arr2d[0,2])

3
3


In [5]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [7]:
arr2d[:2,2]

array([3, 6])

In [9]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])